add banner
lizxqws/fe_1y_1_23-team_1-project-1 pull request #11
Opened 2023-05-29 17:10 UTC by AddNiI

CSS:
.banner{
  background-image:url(assets/bghone.png) ;
  background-size: 1440px 831px;
  background-repeat: no-repeat;
  height: 831px;
  width: 1440px;
}

.bigtext{
  padding : 188px 725px 19px 120px;
  font-family: 'DM Serif Display', serif;
  font-size: 80px;
  color: #292f36;
}

.text{
  padding: 0 743px 35px 120px;
  color: #4D5053;
}
![image](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/100078200/b5751ba2-32bf-43b4-9d65-98d690b56019)
HTML:
![image](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/100078200/e4cb2910-7197-4f44-8bb8-05145026ba9b)

2023-05-30 15:18 UTC, marianaD4 requested changes

2023-05-30 15:18 UTC, marianaD4 commented on main.css
> +  margin: 0 1113px 260px 120px;
Не змінюємо стилі базової кнопки. Додамаємо новий клас і тоді додаємо стилі

2023-05-30 15:18 UTC, marianaD4 commented on main.css
> +  margin: 0 1113px 260px 120px;
Також достатньо тільки margin-left у даному випадку, решту зайві

2023-05-30 15:18 UTC, marianaD4 commented on main.css
> +  background-size: 100% 831px;
достатньо тільки background-size: 100%

2023-05-30 15:18 UTC, marianaD4 commented on main.css
> +  padding : 188px 725px 19px 120px;
тільки padding-left і padding-top буде достатньо

2023-06-06 10:12 UTC, marianaD4 requested changes

2023-06-06 10:12 UTC, marianaD4 commented on index.html
> +        <p class="text">The world needs innovators and problem solvers who turn challenges into greater opportunities.</p>
title i subtitle краще
bigtext - більше схоже на модифікатор, у даному випадку потрібен елемент

2023-06-06 10:12 UTC, marianaD4 commented on main.css
> +  padding : 188px 725px 19px 120px;
зверни увагу на попередній коментар
не хороша практика задавати такі великі padding, тут краще вже використати width

2023-06-06 21:26 UTC, marianaD4 requested changes

2023-06-06 21:26 UTC, marianaD4 commented on main.css
> +  padding: 0 743px 35px 120px;
також краще width написати

2023-06-06 21:26 UTC, marianaD4 commented on main.css
> +  padding: 0 743px 35px 120px;
також краще width написати

2023-06-07 06:29 UTC, AddNiI commented on main.css
> +  padding: 0 743px 35px 120px;
я зрозумiв нащ

2023-06-07 06:30 UTC, AddNiI commented on main.css
> +  padding: 0 743px 35px 120px;
о повторювати?

2023-06-07 20:39 UTC, marianaD4 requested changes

2023-06-07 20:39 UTC, marianaD4 commented on main.css
> +  width: 743px;
перевір ширину на макеті

2023-06-08 04:14 UTC, AddNiI commented on main.css
> +  width: 743px;
![image](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/100078200/499bb3db-6966-4fa7-a28d-936c7de70f0f)

2023-06-09 09:46 UTC, marianaD4 approved these changes

2023-06-09 10:02 UTC, merged