add section with logo and with copyright
lizxqws/fe_1y_1_23-team_1-project-1 pull request #13
Opened 2023-06-01 18:38 UTC by AddNiI

don't end

2023-06-06 21:34 UTC, marianaD4 requested changes
некоректні назви іконок
перейменуй, будь ласка

2023-06-06 21:34 UTC, marianaD4 commented on index.html
> +        </section>
section всередині section?

2023-06-06 21:34 UTC, marianaD4 commented on index.html
> +    <footer class="ftr container">
спочатку загальний клас, потім додаткові нові класи

2023-06-06 21:34 UTC, marianaD4 commented on main.css
> +  width: 1440px;
повинна бути на всю ширину екрану

2023-06-06 21:34 UTC, marianaD4 commented on assets/htoya.png
потрібно перейменувати

2023-06-06 21:39 UTC, marianaD4 requested changes

2023-06-06 21:39 UTC, marianaD4 commented on index.html
> +          <a class="logo" href="http://ru.linkedin.com/"><img src="assets/htoya.png" alt="linkedin"></a>
беремо загальні посилання без прив'язки до мови

2023-06-06 21:39 UTC, marianaD4 commented on main.css
> +  margin: 25px 83px 30px 0;
замість 83px задаємо ширину

2023-06-06 21:39 UTC, marianaD4 commented on main.css
> +
використовуємо псевдоклаc :last-child

2023-06-06 21:39 UTC, marianaD4 commented on main.css
> +  padding: 35px 325px 36px;
325px?
може спробувати text-align i width?

2023-06-06 21:39 UTC, marianaD4 commented on main.css
> +  margin: 141px 120px 129px;
![image](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/124216656/9d6bd440-e2d7-49a9-9090-3def5f31dd3b)

Не  зовсім хороша ідея із 120px

2023-06-06 21:39 UTC, marianaD4 commented on main.css
> +  padding: 100px 333px 9px;
333px?
Коментарі вище

2023-06-06 21:39 UTC, marianaD4 commented on main.css
> +  padding: 31px 485px 95px 474px;
485?

2023-06-06 21:39 UTC, marianaD4 commented on main.css
> +  padding: 0 414px 0 415px;
414 i 415?

2023-06-07 06:07 UTC, AddNiI commented on index.html
> +        </section>
<section class="contactUs">
        <h2 class="Wjti">Wanna join the interno?</h2>
        <p class="CUGaFC">Contact Us & Get a Free Consultation</p>
        <section class="lastbutton">
          <button class="button button-arrow-round">Connect With us<img alt="strilka" src="photo.button/2.png"></button>
        </section>
це для розмiщення кнопки

2023-06-07 06:08 UTC, AddNiI commented on index.html
> +    <footer class="ftr container">
вiд змiни положення доданкiв сума не змiнюеться

2023-06-07 06:09 UTC, AddNiI commented on main.css
> +  width: 1440px;
у завданнi не було таке прописано

2023-06-07 06:11 UTC, AddNiI commented on main.css
> +  margin: 25px 83px 30px 0;
2 width?
![image](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/100078200/5a37a32e-58b9-4cac-9810-5c6e22e6000a)

2023-06-07 06:11 UTC, AddNiI commented on main.css
> +
я використовую псевдобукви

2023-06-07 06:14 UTC, AddNiI commented on main.css
> +  padding: 35px 325px 36px;
розумiю
![image](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/100078200/7188b6af-0f06-4b31-ac8e-0a82ed698db4)

2023-06-07 06:16 UTC, AddNiI commented on main.css
> +  padding: 35px 325px 36px;
![msedge_sCmZAEE3ez](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/100078200/7b19fc28-7a3e-4280-a6db-b612f2834a4c)

2023-06-07 06:17 UTC, AddNiI commented on main.css
> +  margin: 141px 120px 129px;
сайт розробляеться пiд екрани 1440pExcel

2023-06-07 06:18 UTC, AddNiI commented on main.css
> +  padding: 100px 333px 9px;
help him
![image](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/100078200/2b042db6-e242-4060-9d40-b6de628e0941)

2023-06-07 06:19 UTC, AddNiI commented on main.css
> +  padding: 31px 485px 95px 474px;
хто я
![image](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/100078200/612d9a7c-5b41-4d29-b646-8d66de272908)

2023-06-07 06:20 UTC, AddNiI commented on main.css
> +  padding: 31px 485px 95px 474px;
головне що поцентру
![image](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/100078200/9f001b4e-ef25-4970-b9a6-be19761dd99f)

2023-06-07 06:24 UTC, AddNiI commented on main.css
> +  padding: 0 414px 0 415px;
![image](https://github.com/lizxqws/fe_1y_1_23-team_1-project-1/assets/100078200/f63dbf0b-17c2-4ea2-9225-74493629b847)
чи треба перевернути i через width?

2023-06-07 20:31 UTC, marianaD4 commented on index.html
> +        </section>
семантично так неправильно
а div тег для розміщення кнопки не підходить?

2023-06-07 20:33 UTC, marianaD4 commented on main.css
> +  margin: 141px 120px 129px;
так, вірно під 1440px
але якщо з обох сторін по 120px відступу. Отже - текст повинен бути по центру

2023-06-07 20:37 UTC, marianaD4 requested changes

2023-06-07 20:37 UTC, marianaD4 commented on main.css
> +  padding: 100px 333px 9px;
може варто подума про інший підхід?
Як стосовно text-align?

2023-06-09 07:15 UTC, merged